version: '3.8'

services:
  radio-bot:
    build: .
    container_name: super-radio
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./music:/app/music
      - ./data:/app/data
      - ./xtunnel:/usr/local/bin/xtunnel  # Монтируем xTunnel в контейнер
    environment:
      - TELEGRAM_BOT_TOKEN=8726694308:AAF5_WwE1Tu9csG7ZKjwgG50n-1A5nByM4Q
