music_directory    "/music"
playlist_directory "/var/lib/mpd/playlists"
db_file            "/var/lib/mpd/mpd.db"
log_file           "/var/log/mpd/mpd.log"
pid_file           "/run/mpd/mpd.pid"
state_file         "/var/lib/mpd/mpdstate"

user               "mpd"
group              "audio"

bind_to_address    "0.0.0.0"
port               "6600"

# Основной аудиовыход – в Icecast
audio_output {
    type            "shout"
    name            "Icecast"
    host            "icecast"
    port            "8000"
    mount           "/radio.mp3"
    password        "hackme"
    bitrate         "128"
    format          "44100:stereo:16"
    encoding        "mp3"       # или "ogg"
    protocol        "icecast2"
    description     "Super Radio"
    genre           "Various"
    public          "yes"
}

# Локальный выход, чтобы MPD не падал, если Icecast отключится
audio_output {
    type            "null"
    name            "null"
}
